version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint-django
    versions:
    - 2.4.3
  - dependency-name: pre-commit
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: django-extensions
    versions:
    - 3.1.2
  - dependency-name: django
    versions:
    - 3.1.8
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: ipdb
    versions:
    - 0.13.5
    - 0.13.6
  - dependency-name: defusedxml
    versions:
    - 0.7.0
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
  - dependency-name: pillow
    versions:
    - 8.1.1
  - dependency-name: mypy
    versions:
    - "0.800"
