exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1  # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations  # force type annotations
      - id: python-check-blanket-noqa  # force specific noqa lines
  - repo: https://github.com/PyCQA/pydocstyle.git
    rev: '5.0.2'
    hooks:
      - id: pydocstyle
  - repo: https://github.com/PyCQA/bandit
    rev: '1.6.2' # Update me!
    hooks:
    - id: bandit
