[tool.poetry]
name = "infinity_tracker"
version = "0.1.0"
description = ""
authors = ["jokajak <jokajak@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1"
Django = "^3.0.8"

[tool.poetry.dev-dependencies]
pre-commit = "^2.6.0"
black = "^19.10b0"
flake8 = "^3.8.3"
pytest = "^6.0.1"
pytest-django = "^3.9.0"
pytest-cov = "^2.10.0"
pytest-xdist = "^1.34.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
