# Generated by Django 3.1 on 2020-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('enabled', models.BooleanField()),
                ('current_activity', models.IntegerField(choices=[(1, 'Home'), (2, 'Sleep'), (3, 'Away'), (4, 'Awake'), (5, 'Manual')])),
                ('current_temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_humidity', models.PositiveIntegerField()),
                ('fan', models.IntegerField(choices=[(1, 'Low')])),
                ('heat_set_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cool_set_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hold', models.CharField(max_length=100)),
                ('otmr', models.CharField(max_length=100)),
                ('zone_conditioning', models.IntegerField(choices=[(1, 'Low')])),
                ('damper_position', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hvac',
            name='cool_set_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hvac',
            name='heat_set_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
