name: Docs

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USE_DOCKER: no

    steps:
    - uses: actions/checkout@v2
    - name: Set up newest Python
      uses: actions/setup-python@v2
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Python Dependencies
      run: poetry install

    - name: Generate API docs
      run: |
        poetry run sphinx-apidoc -o docs/_source/api infinity_tracker/
        poetry run sphinx-apidoc -o docs/_source/api proxy/
        poetry run sphinx-apidoc -o docs/_source/api hvac/

    - name: Build documentation
      run: poetry run make -C docs html

    # Publish built docs to gh-pages
    - name: Publish to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        publish_branch: gh-pages

